config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  #get '/inicio', to: 'welcome#index'

  resources :moedas
   #get '/moedas', to:'moedas#index'

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moeda.rb
class Moeda < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/moedas_controller.rb
class MoedasController < ApplicationController
  #layout "adm"

  before_action :set_moeda, only: [:show, :edit, :update, :destroy]

  # GET /moedas
  # GET /moedas.json
  def index
    @moedas = Moeda.all
  end

  # GET /moedas/1
  # GET /moedas/1.json
  def show
  end

  # GET /moedas/new
  def new
    @moeda = Moeda.new
  end

  # GET /moedas/1/edit
  def edit
  end

  # POST /moedas
  # POST /moedas.json
  def create
    @moeda = Moeda.new(moeda_params)

    respond_to do |format|
      if @moeda.save
        format.html { redirect_to @moeda, notice: 'Moeda foi criada com Sucesso.' }
        format.json { render :show, status: :created, location: @moeda }
      else
        format.html { render :new }
        format.json { render json: @moeda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moedas/1
  # PATCH/PUT /moedas/1.json
  def update
    respond_to do |format|
      if @moeda.update(moeda_params)
        format.html { redirect_to @moeda, notice: 'Moeda foi editada com Sucesso.' }
        format.json { render :show, status: :ok, location: @moeda }
      else
        format.html { render :edit }
        format.json { render json: @moeda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moedas/1
  # DELETE /moedas/1.json
  def destroy
    @moeda.destroy
    respond_to do |format|
      format.html { redirect_to moedas_url, notice: 'Moeda foi apagada com Sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moeda
      @moeda = Moeda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moeda_params
      params.require(:moeda).permit(:descricao, :acronimo, :url_image, :valor_reais)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @meu_nome = params[:nome]
    @curso = params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_br(data_us)
    data_us.strftime("%d/%m/%Y")
  end

  def ambiente_rails
    if Rails.env.development?
      "Desenvolvimento"
    elsif Rails.env.production?
      "Producao"
    else
      "Teste"
    end
  end

end

app/helpers/moedas_helper.rb
module MoedasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CryptoWallet</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<h1> CABECALHO - ADM </h1>
<%= yield %> <%# index.html.erb, edit.html.erb %>
<h1> RODAPE - ADM </h1>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1> CABECALHO </h1>
    <%= yield %> <%# index.html.erb, edit.html.erb %>
  <h1> RODAPE </h1>
  </body>
</html>

app/views/moedas/_form.html.erb
<%= form_with(model: moeda, local: true) do |form| %>
  <% if moeda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(moeda.errors.count, "error") %> prohibited this moeda from being saved:</h2>

      <ul>
      <% moeda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :"Sigla" %>
    <%= form.text_field :acronimo %>
  </div>

  <div class="field">

    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
    <%#= image_tag moeda.url_image, width:25, heidth:25 %>
  </div>

  <div class="field">
    <%= form.label :valor_reais %>
    <%= form.text_field :valor_reais %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moedas/edit.html.erb
<h1>Editing Moeda</h1>

<%= render 'form', moeda: @moeda %>

<%= link_to 'Mostrar', @moeda %> |
<%= link_to 'Voltar', moedas_path %>

app/views/moedas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moedas</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Sigla</th>
      <th>Imagem</th>
      <th>Valor Reais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moedas.each do |moeda| %>
      <tr>
        <td><%= moeda.descricao %></td>
        <td><%= moeda.acronimo %></td>
        <td><%= image_tag moeda.url_image, width:25, heidth:25 %></td>
        <td><%= moeda.valor_reais %></td>
        <td><%= link_to 'Mostrar', moeda %></td>
        <td><%= link_to 'Editar', edit_moeda_path(moeda) %></td>
        <td><%= link_to 'Deletar', moeda, method: :delete, data: { confirm: 'Tem certeza ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Moeda', new_moeda_path %>

app/views/moedas/new.html.erb
<h1>New Moeda</h1>

<%= render 'form', moeda: @moeda %>

<%= link_to 'Voltar', moedas_path %>

app/views/moedas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @moeda.descricao %>
</p>

<p>
  <strong>Acronimo:</strong>
  <%= @moeda.acronimo %>
</p>

<p>
  <strong>Url image:</strong>
  <%= image_tag @moeda.url_image, width:25, heidth:25 %>
<p>
  <strong>Valor reais:</strong>
  <%= @moeda.valor_reais %>
</p>

<%= link_to 'Editar', edit_moeda_path(@moeda) %> |
<%= link_to 'Voltar', moedas_path %>

app/views/welcome/_menu.html.erb
<ul>
  <li>
  <%= link_to "Cadastro de Moedas",  moedas_path %>
  </li>
</ul>

app/views/welcome/index.html.erb
<h1>Seja Bem-Vindo</h1>
<p> <strong> Data:</strong> <%= data_br(Date.today) %></p>

<%= render "menu" %>

<p>
  Voce está em ambiente de <strong><%= ambiente_rails %></strong>
</p>

<p>
 Eu sou uma variavel de instancia/sessao <strong><%= @meu_nome %></strong>
</p>

<p>
  Meu curso é o curso de <strong><%= @curso %></strong>
</p>